apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: chachkies-api
  name: chachkies-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chachkies-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chachkies-api
    spec:
      containers:
        - image: chachkies-api:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          name: app
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /actuator/health/readiness
              port: 8080
