apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: chachkies-api
  name: chachkies-api
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: chachkies-api
  sessionAffinity: None
  type: ClusterIP